# Generated by Django 4.1.1 on 2022-09-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('createdBy', models.CharField(default='Guest', max_length=50)),
                ('comment', models.TextField(default='Its a licence mate')),
            ],
        ),
    ]
