# Generated by Django 4.1.1 on 2022-09-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='licence',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='licence',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='licence',
            name='licence_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='licence.licencetype'),
        ),
    ]
