# Generated by Django 4.1.1 on 2022-09-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0002_licencetype_rename_createdby_licence_created_by_and_more'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO licence_licencetype (name) VALUES ('Microsoft Office'), ('Visual Studio Professional'), ('Resharper standard'), ('Resharper professional'), ('JetBrains'), ('Telerik UI for WPF');")
    ]
