# Generated by Django 4.1.1 on 2022-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0004_remove_licence_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='licence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licencetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
